Added discrete states (Closes #117)
nasa/progpy pull request #178
Opened 2024-12-11 21:04 UTC by teubert

Closes #177 

Adds the option of discrete states to ProgPy. Discrete states are implemented by initializing a state using the Discrete State Object

2025-02-13 15:55 UTC, lymichelle21 reviewed
As mentioned during the PR review meeting, adding a note on what the expected behavior should be for the sequential discrete states if the first state is 0 and we subtract from it (should it throw an error, stay at 0, or loop circularly to the highest state?)

2025-03-04 21:34 UTC, lymichelle21 requested changes
Jupyter notebook runs and examples make sense

2025-03-04 21:34 UTC, lymichelle21 commented on tests/test_surrogates.py
> +        MSE = surrogate.calc_error(result.times, result.inputs, result.outputs)
I tried running the tests, and I'm getting the following error. The tests run fine on the dev branch but I'm not sure exactly what change in this PR impacted the test - potentially here?

```
======================================================================
ERROR: test_generate_surrogate (tests.test_examples.TestExamples.test_generate_surrogate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mly1/Documents/progpy/tests/test_examples.py", line 22, in test
    ex.run_example()
  File "/Users/mly1/Documents/progpy/examples/generate_surrogate.py", line 160, in run_example
    MSE = batt.calc_error(simulated_results.times, simulated_results.inputs, simulated_results.outputs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mly1/Documents/progpy/src/progpy/prognostics_model.py", line 1269, in calc_error
    return method(self, times, inputs, outputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mly1/Documents/progpy/src/progpy/utils/calc_error.py", line 201, in MSE
    return err_total/counter
           ~~~~~~~~~^~~~~~~~
ZeroDivisionError: division by zero

----------------------------------------------------------------------
Ran 27 tests in 203.441s

FAILED (errors=1)
```

2025-03-10 17:00 UTC, lymichelle21 commented on tests/test_surrogates.py
> +        MSE = surrogate.calc_error(result.times, result.inputs, result.outputs)
Upon closer inspection, the issue seems to be traced back to the changes in `containers.py` - I tried running the  tests (`test_examples.py`) without these changes and it passed.

2025-03-10 20:18 UTC, lymichelle21 commented on tests/test_surrogates.py
> +        MSE = surrogate.calc_error(result.times, result.inputs, result.outputs)
Issue with None and nan handled offline - all tests run successfully now :)

2025-03-11 00:00 UTC, kjjarvis requested changes
Just a few minor suggestions and a question about the small_rotorcraft.py changes. Also, I'm getting a failed test on line 49 of test_discrete_states.py. Sounds like @lymichelle21 didn't get the same error so let's debug together on Wednesday

2025-03-11 00:00 UTC, kjjarvis commented on src/progpy/models/aircraft_model/small_rotorcraft.py
> +        x['vx'] += dt*((sin_theta * cos_psi * cos_phi + sin_phi * sin_psi) * T - fe_drag[0]) / m
Should the division by m be included in the parenthesis, so that the entire value is multiplied by dt here? 

I see the same for vy, p, q, and r, so perhaps I'm not thinking about it correctly. If my logic is incorrect, and the division should not be included, then does vz need to be changed to be consistent with this?

2025-03-14 21:12 UTC, lymichelle21 commented
Tests all run successfully :)

2025-03-17 18:28 UTC, lymichelle21 approved these changes
LGTM

2025-04-02 19:38 UTC, teubert commented on src/progpy/models/aircraft_model/small_rotorcraft.py
> +        x['vx'] += dt*((sin_theta * cos_psi * cos_phi + sin_phi * sin_psi) * T - fe_drag[0]) / m
We discussed this and decided they were functionally the same, so the parenthesis aren't needed

2025-04-02 19:44 UTC, kjjarvis approved these changes
Looks good!

2025-04-02 19:46 UTC, merged